# Makefile for ENTE-TCP Kernel Module
#
# ENTE-TCP: Entropy-Enhanced TCP Congestion Control
# Based on: NDM-TCP (https://github.com/hejhdiss/lkm-ndm-tcp)
# Simplified version with ML components removed
# Author: ENTE-TCP Development Team (@hejhdiss)
# Generated by: Claude Sonnet 4.5 (Anthropic)
#
# Usage:
#   make              - Build the kernel module
#   make clean        - Remove build artifacts
#   make install      - Install the module (requires root)
#   make uninstall    - Remove the module (requires root)
#   make load         - Load the module into kernel (requires root)
#   make unload       - Unload the module from kernel (requires root)
#   make test         - Load module and set as default congestion control

# Module name
obj-m += ente_tcp_lkm.o

# Kernel build directory
KDIR := /lib/modules/$(shell uname -r)/build

# Current directory
PWD := $(shell pwd)

# Compiler flags for the module
ccflags-y := -O2 -Wall

# Default target - build the module
all:
	@echo "Building ENTE-TCP kernel module..."
	$(MAKE) -C $(KDIR) M=$(PWD) modules
	@echo "Build complete! Module: ente_tcp_lkm.ko"

# Clean build artifacts
clean:
	@echo "Cleaning build artifacts..."
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	rm -f *.o *.ko *.mod.c *.mod *.order *.symvers
	@echo "Clean complete!"

# Install module to system
install: all
	@echo "Installing ENTE-TCP module..."
	sudo $(MAKE) -C $(KDIR) M=$(PWD) modules_install
	sudo depmod -a
	@echo "Module installed!"

# Uninstall module from system
uninstall:
	@echo "Uninstalling ENTE-TCP module..."
	sudo rm -f /lib/modules/$(shell uname -r)/extra/ente_tcp_lkm.ko
	sudo depmod -a
	@echo "Module uninstalled!"

# Load the module into kernel
load: all
	@echo "Loading ENTE-TCP module..."
	sudo insmod ente_tcp_lkm.ko
	@echo "Module loaded! Check with: lsmod | grep ente_tcp"
	@dmesg | tail -n 5

# Unload the module from kernel
unload:
	@echo "Unloading ENTE-TCP module..."
	sudo rmmod ente_tcp_lkm
	@echo "Module unloaded!"
	@dmesg | tail -n 2

# Test - load module and set as default
test: load
	@echo ""
	@echo "=== Testing ENTE-TCP ==="
	@echo "Current congestion control algorithms:"
	@sysctl net.ipv4.tcp_available_congestion_control
	@echo ""
	@echo "Setting ENTE-TCP as default..."
	@sudo sysctl -w net.ipv4.tcp_congestion_control=ente_tcp
	@echo ""
	@echo "Current default:"
	@sysctl net.ipv4.tcp_congestion_control
	@echo ""
	@echo "Module info:"
	@modinfo ente_tcp_lkm.ko

# Show module information
info:
	@echo "=== ENTE-TCP Module Information ==="
	@modinfo ente_tcp_lkm.ko 2>/dev/null || echo "Module not built yet. Run 'make' first."

# Show kernel messages related to ENTE-TCP
dmesg:
	@echo "=== ENTE-TCP Kernel Messages ==="
	@dmesg | grep -i ente || echo "No ENTE-TCP messages found"

# Check if module is loaded
status:
	@echo "=== ENTE-TCP Status ==="
	@echo "Module loaded:"
	@lsmod | grep ente_tcp || echo "  Not loaded"
	@echo ""
	@echo "Available congestion control:"
	@sysctl net.ipv4.tcp_available_congestion_control
	@echo ""
	@echo "Current default:"
	@sysctl net.ipv4.tcp_congestion_control

# Help target
help:
	@echo "ENTE-TCP Kernel Module Makefile"
	@echo ""
	@echo "Available targets:"
	@echo "  make             - Build the kernel module"
	@echo "  make clean       - Remove build artifacts"
	@echo "  make install     - Install module to system (requires root)"
	@echo "  make uninstall   - Remove module from system (requires root)"
	@echo "  make load        - Load module into kernel (requires root)"
	@echo "  make unload      - Unload module from kernel (requires root)"
	@echo "  make test        - Load and set as default (requires root)"
	@echo "  make info        - Show module information"
	@echo "  make dmesg       - Show kernel messages"
	@echo "  make status      - Check module and congestion control status"
	@echo "  make help        - Show this help message"
	@echo ""
	@echo "Quick start:"
	@echo "  1. make          - Build the module"
	@echo "  2. make test     - Load and test the module"
	@echo "  3. make status   - Verify it's working"

.PHONY: all clean install uninstall load unload test info dmesg status help